FROM quay.io/keycloak/keycloak:latest as builder

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG HOSTNAME
# Railway should automatically specify this port
ARG PORT

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres

RUN /opt/keycloak/bin/kc.sh build --db=postgres

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin

ENV KC_HTTP_PORT=${PORT}
ENV KC_HTTP_HOST=0.0.0.0
ENV KC_PROXY=edge

ENV KC_DB_URL=${DB_URL}
ENV KC_DB_USERNAME=${DB_USERNAME}
ENV KC_DB_PASSWORD=${DB_PASSWORD}
ENV KC_HOSTNAME=${HOSTNAME}